### ISSUE TITLE
Not working ???

### ISSUE THREAD

**Issue by KhoiTrant68** [CaiShilv/HiFi-VRIC#1]
When I try to train with the custom dataset, it does not work. The issue is the shape of the input image, so I think your code has a problem with the data loader.

**Comment by CaiShilv** [comment]
Before running, prepare the .csv file of the dataset. Are you ready?

**Comment by KhoiTrant68** [comment]
Yes, I did

**Comment by CaiShilv** [comment]
The dataset images we use are at least 256 * 256 RGB images. You need to ensure that each image of the dataset you use meets this condition.

**Comment by KhoiTrant68** [comment]
Does your model only work for test images with shapes is even number sizes such as 1024x1024?

**Comment by KhoiTrant68** [comment]
I ensure about the size of my images.

**Comment by CaiShilv** [comment]
When testing, the image size should be no less than 64 * 64. The size is not fixed.

**Comment by KhoiTrant68** [comment]
I understand the condition but in "def squeeze2d(input, factor=2):" in our_utils.py  , the condition for the test image is h and w is even numbers.

**Comment by CaiShilv** [comment]
In the test, we solved this problem by filling the image several times to 64. You can see line 56 in eval.py.

**Comment by KhoiTrant68** [comment]
![image](https://user-images.githubusercontent.com/85048572/207289819-224aabaa-c804-40f9-9c86-272671234a64.png)

Here is the test function in train.py. Should I add pad.pad(x, 64) apter line 51?

**Comment by CaiShilv** [comment]
In the training process, we default that the kodak dataset meets the conditions. If it is your own test set, you need to add it manually.

**Comment by KhoiTrant68** [comment]
Many thanks, sir !!
