### ISSUE TITLE
Test VTM with kodak dataset

### ISSUE THREAD

**Issue by LHB116** [CaiShilv/HiFi-VRIC#3]
I am trying to test kodak dataset use VTM codec with the command: python -m compressai.utils.bench vtm ./kodim -b ./VVCSoftware_VTM-VTM-12.1/bin -c ./VVCSoftware_VTM-VTM-12.1/cfg/encoder_intra_vtm.cfg -q 12 17 22 27 32 37 42 47 -j 24. But get worse result than your paper's.  I am using orginal 768x512 or 512x768 images in Kodak dataset. If I use the dataset to test bpg or other pretrained deep image codec, I can get same results with CompressAI. Can you tell me how do you test kodak dataset use VTM codec?
result:
{
  "name": "VTM",
  "description": "VTM",
  "results": {
    "bpp": [
      1.4310870700412328,
      1.1849322848849826,
      0.9710701836480037,
      0.784409417046441,
      0.6259062025282118,
      0.49040137396918393,
      0.3769209120008681,
      0.28607177734375006,
      0.21201070149739584,
      0.15513695610894096
    ],
    "psnr": [
      39.376790247559306,
      38.44499331100548,
      37.4208194248964,
      36.315253798837844,
      35.17724886235666,
      33.99820465191855,
      32.81709898226944,
      31.66461774953432,
      30.518182550138793,
      29.44167385471475
    ]
  }
}

**Comment by CaiShilv** [comment]
I ran it directly from the official VTM source code instead of compressai. The official URL is https://vcgit.hhi.fraunhofer.de/jvet/VVCSoftware_VTM/-/tree/VTM-12.1. There is a tutorial inside.
